# Generated by Django 6.1 on 2026-08-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Survey Mission', max_length=140)),
                ('time_estimate', models.DurationField(blank=True, null=True)),
                ('waypoints_count', models.PositiveIntegerField(default=0)),
                ('current_wp', models.PositiveIntegerField(default=0)),
                ('total_distance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('STABILIZED', 'Stabilized'), ('READY', 'Ready')], default='INACTIVE', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(default='NORMAL', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='LDOS-001', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('altitude', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('sats', models.IntegerField(blank=True, null=True)),
                ('fix3d', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('uptime', models.IntegerField(blank=True, default=0, null=True)),
                ('live_image_url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WarningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('level', models.CharField(choices=[('low', 'Low'), ('high', 'High')], default='low', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
