# Generated by Django 6.1 on 2026-08-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetry',
            old_name='device_name',
            new_name='device_id',
        ),
    ]
