# Generated by Django 6.0.8 on 2026-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='device_id',
            field=models.CharField(default='device_1', max_length=100),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='distance_from_home',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
