# Generated by Django 6.0.8 on 2026-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_telemetry_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Survey Mission', max_length=140)),
                ('time_estimate', models.DurationField(blank=True, null=True)),
                ('waypoints_count', models.PositiveIntegerField(default=0)),
                ('current_wp', models.PositiveIntegerField(default=0)),
                ('total_distance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PayloadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('STABILIZED', 'Stabilized'), ('READY', 'Ready')], default='INACTIVE', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(default='NORMAL', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WarningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('level', models.CharField(choices=[('low', 'Low'), ('high', 'High')], default='low', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='telemetry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='distance_from_home',
            new_name='altitude',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='humidity',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='pressure',
            new_name='speed',
        ),
        migrations.AddField(
            model_name='telemetry',
            name='battery_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='fix3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='live_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='sats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='uptime',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='device_id',
            field=models.CharField(default='LDOS-001', max_length=100),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
